### ISSUE TITLE
Shorewall integration

### ISSUE THREAD

**Issue by baccenfutter** [blunix/formula-letsencrypt#13]
With our new `formula-shorewall` we now by default install a firewall on every minion. Frankly, if we want to do LetsEncrypt domain-validations (requests AND renewals) we have to selectively allow this inbound traffic for the time being and close the port again after the validation process has ended.

We can leverage `cmd.run` for this task and fire shorewall CLI commands like so:
```
shorewall open <source> <dest> [ <protocol> [ <port> ] ]
e.g.: shorewall open all 1.2.3.4 tcp 80
```

and respectively:
```
shorewall close <source> <dest> [ <protocol> [ <port> ] ]
e.g.: shorewall close all 1.2.3.4 tcp 80
```

**Comment by baccenfutter** [comment]
Cc: @p-thurner

**Comment by p-thurner** [comment]
formula is depricated, closed.
